#!/bin/bash
set -e

case "$1" in
  remove|purge)
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop sima-mipi-util.service || true
        systemctl disable sima-mipi-util.service || true
    fi
    ;;
esac
exit 0
